---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 1.17.3
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      WAIT_FOR_JEKYLL: 10
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - bundle_and_test:
          name: ruby2-6
          ruby_version: 2.6.3
      - bundle_and_test:
          name: ruby2-5
          ruby_version: 2.5.5
      - bundle_and_test:
          name: ruby2-4
          ruby_version: 2.4.6
